# Generated by Django 2.1.5 on 2019-05-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190502_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
